### ISSUE TITLE
Next  step: Docker Technologie?

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#10]
What is docker ?
all developer uses it  but why?

@idrice24  not do to, maybe next year 🗡️

**Comment by idrice24** [comment]
- Docker is a popular open-source project based on Linux containers. Docker is written in go and developed by Dotcloud (A PaaS Company). It is basically a container engine that uses the Linux Kernel features like namespaces and control groups to create containers on top of an operating system.
- it is a tool designed to make it easier to create, deploy, and run applications by using containers.
