### ISSUE TITLE
Readme typo error 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#12]
1. On the section Technologies (IDE) why IDE in parenthese?
2.  I think  you don t need this IDE help us to: 
3. >Neteans IDE  and  this IDE help us to should  not be to separated.
4. The under section should be  removed. you just need only one (empty circle should be removed)
5. **#Client Side??
6. Installation section, i don t understand?

**Comment by idrice24** [comment]
The IDE is in parenthese because i use it in some part of the project and not on all.

**Comment by idrice24** [comment]
User don't need to install any thing. they just have to click on the link that i will give at the end of the project. this link will direct them on the software. there the will start use it.
