### ISSUE TITLE
Wiki page is missing

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#2]
Each project should get a wiki page  see  TAB **Wiki** in Github
This project misses a wiki page to explain  more about technologie and modules in your software.

TODO:
Adding Wiki page which contains e.g.
- What does POM.xml file? your own words
- Explain each external Dependency  that you use (List in POM.xml )
- Alternative of Technolgie (Server side and client Side)

**Comment by idrice24** [comment]
- i explain it in the pom file as a comment

- i have explained each dependency in the pom by commentting it in the pom

- still to come

**Comment by Ghislain1** [comment]
On the section " What is inside"
Spring Data(Hibernate & MySQL), Spring MVC and Thymleaf not work when  the link is clicked!!
Can you check the reference links again!!

**Comment by idrice24** [comment]
it is now ok.
the links functions well.!!

**Comment by Ghislain1** [comment]
springboot-crud-demo??
this is not a correct title for a heading , am i not right?

**Comment by Ghislain1** [comment]
Your readMe file is not complete!!  missing e.g:
- IDE that you use ? Not only for java code , but for html, css, angular
-Technologie Client and sever  , each should et his own  sub-heading
