### ISSUE TITLE
[Proposal] Deploying to the Cloud

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#21]
I found  a way how to host any server-side software
 
this is a link 

https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html

Just read it and let ne konw!

For client  you can use guthub page
my own sample has been done with github page.

**Comment by idrice24** [comment]
done!!

**Comment by Ghislain1** [comment]
Where have you done it !!
Can you send me a  link..

IF IT s NOT WORK.. DON'T WRITE DONE--> That's lazy

**Comment by idrice24** [comment]
https://dashboard.heroku.com/apps/idrice24sms
