### ISSUE TITLE
Copyright (c) 2020 SAP SE or an SAP affiliate company.

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#23]
**Describe the bug**
Copyright name is wrong

**To Reproduce**
1. Go to 'read me file'
2. Click on 'Liscence'
3. See error

**Expected behavior**
Your own name  or use MIT Liscence

**Additional context**
You can also read which of license you should use. (MIT, APACHE... )

**Comment by idrice24** [comment]
i have change the name to IDRICE24. i think now is ok!
