### ISSUE TITLE
Searching for  Database Hosting for our feature project

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#27]
Please can list all Database hosting hier:
Just google and find a free Database hosting that we can use for a long time.
1. https://www.freemysqlhosting.net/
     * Free
     * 5MB only
     * MySQL Database is used
    

**Put your findings the same like above**

**Comment by idrice24** [comment]
- firebase (free trial)
- MySQL.
- PostgreSQL.
- NuoDB.
- MariaDB.
- Oracle Database XE.
- MarkLogic.
- Azure SQL Database.
- Google App Engine.
