### ISSUE TITLE
Installation of you Software on PC

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#3]
Do you have any feature or idea how to create a **setup** for installation of your software on
- Window system (MUST)
- Mac System  and so on...

For a first version of your application: It s better to  find  the way  to use your software without GITHUB site.

**Comment by idrice24** [comment]
This step i will do it went the project will be at 80%

**Comment by Ghislain1** [comment]
You cannot close the issue when you want to solve it in future!!!

**Comment by Ghislain1** [comment]
We  close an issue when it  is solved!!  am i m not right?
