### ISSUE TITLE
License sentence is wrong

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#31]
rewrite license sentence 

DON't put this name 
Copyright (c) 2020 SAP SE or an SAP affiliate company

You can get trouble with that.

**Comment by idrice24** [comment]
At which part of the license?

**Comment by Ghislain1** [comment]
You  use  the name of compagny.. it s not  good

**Comment by idrice24** [comment]
i have changed that name to IDRICE24
