### ISSUE TITLE
Review your read me file 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#33]
Hello Idrice,
 Can you review yourself our read me file?
There are many errors threre, i dont want to o through each error and make an issue  for that.

You have to work seriously!!
Error Check list:
1.  Take a time a  read from top to bottom of ReadMe file --> No a joke
1. Links  by clicking which  not work removed that
1. Legacy Name of people, compagny, and so on remove it--> Justice can poursuit you
1. Use your wiki  to explain your  used technologie
1. Misstake or typo error should be avoived--> this is not professional

**Comment by idrice24** [comment]
1 , 2, 3 done!!

**Comment by Ghislain1** [comment]
Assign a label for this issue

**Comment by idrice24** [comment]
Done!!
