### ISSUE TITLE
[prior] Spring Boot and JPA using PostgreSQL

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#43]
Todo1:
1. Investigate if possible to change MySQL to PostgreSQL
1.  Investigate MySQL vs. PostgreSQL
1. List required of using PostgresSQL on local machine
1. Add it to your project
1. Check PosgreSQL is  free on **heroku**

See sample [ using PostgresSQL](https://developer.okta.com/blog/2018/12/13/build-basic-app-spring-boot-jpa)

**Comment by idrice24** [comment]
1) Yes is it posible ( we need to download postgreSql)
2) PostgreSql are use in apps that need  read/write speed While Mysql database are use for it straightforward data transactions for web apps
3) postgreSQl server (pgLoader)
4) 
5)done!!
