### ISSUE TITLE
Status on read me should be added

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#48]
Add Icon for  Build Status for
* CircleCi  --> Red if error occurs otherwise green
* Issues  --> Display nummber of issue for this project 
 
Ref--> [Build Status on read me file on top](https://github.com/corona-warn-app/cwa-server)

**Comment by idrice24** [comment]
<a href="https://github.com/idrice24/School-Management-Software/issues/" title="Open Issues"><img src="https://img.shields.io/github/issues/idrice24/School-Management-Software?style=flat-square "></a>
<a href="https://github.com/idrice24/School-Management-Software/tree/master/.circleci/" title="Circleci"><img src="https://img.shields.io/circleci/build/github/idrice24/School-Management-Software?color=red&logo=red&style=flat-square?style=flat-square"></a>
