### ISSUE TITLE
ThirdPartyNotices.md is wrong wrong wrong!!

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#49]
I gave you sample how to fill the file ThirdPartyNotices.md

https://github.com/corona-warn-app/cwa-server/blob/master/THIRD-PARTY-NOTICES

**FORMAT:**
Component: XXXXX
Licensor:  YYYYY
Website:   https://aaaaaaaaaaa/
License:   AAAAAAAAAAAAAAAAAA

Is it difficult ? 
Just  make the same **without copy&paste!!**

AVOID COPY AND PASTE

**Comment by idrice24** [comment]
no it is not difficult!!

**Comment by idrice24** [comment]
https://github.com/idrice24/School-Management-Software/blob/master/ThirdPartyNotices.md
