### ISSUE TITLE
Give a label to each Issue 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#50]
From Issue list give a label.
You have access  write right!!

I hope you know how to give a label to  issue on github

Labels are:
 Bug, community, duplicate,  help wanted .. and so on

**Comment by idrice24** [comment]
<a href="https://github.com/idrice24/School-Management-Software/issues/" title="Open Issues"><img src="https://img.shields.io/github/issues/idrice24/School-Management-Software?style=flat-square "></a>
<a href="https://github.com/idrice24/School-Management-Software/tree/master/.circleci/" title="Circleci"><img src="https://img.shields.io/circleci/build/github/idrice24/School-Management-Software?color=red&logo=red&style=flat-square?style=flat-square"></a>

**Comment by idrice24** [comment]
i hope it is what you where asking for!!
