### ISSUE TITLE
Label click for circleci send to wrong page

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#52]
Label on the top on read 👍 
But
1. click on it should open the ci inside circle --> see Corona Server app

https://github.com/corona-warn-app/cwa-server
click on label provides this page  -->  https://app.circleci.com/pipelines/github/corona-warn-app/cwa-server

**Comment by idrice24** [comment]
https://app.circleci.com/pipelines/github/idrice24/School-Management-Software
