### ISSUE TITLE
[prior] Create THIRD-PARTY-NOTICES still not correct

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#53]
What lacking there is not important
you have to understand what this file should store..
you   gets example in corona-warm-server

Make it the same!!

https://github.com/corona-warn-app/cwa-server/blob/master/THIRD-PARTY-NOTICES

**Comment by idrice24** [comment]
https://github.com/idrice24/School-Management-Software/blob/master/ThirdPartyNotices.md
