### ISSUE TITLE
Provide a sql file to init database directly

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#57]
As a test-user (Not normal user) i want to login with default user information!!
1. Can you provide a sql file  to default user?
1. Add howtos in your wiki page after DATABase Configuration
1. Give a label for this issue

**Comment by idrice24** [comment]
1) https://github.com/idrice24/School-Management-Software/blob/master/documents/DB.sql
2) https://github.com/idrice24/School-Management-Software/wiki
3) done
