### ISSUE TITLE
Postgres VS.  MySQL 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#63]
Create a table to compare thoses technologies
Table should  gets:
1. 2 Columns and many rows
1. Each rows should contains  Pro  or Contra  according to technologie
1. Table should be in **your wiki page**

Examples of rows in table:
| Postgres|  MySQL|
| ---------|----------|
| less popular | more popular|
| highly extensible            | low extensible  |

**Comment by idrice24** [comment]
|DBMS	|	MySQL	|	PostgreSQL	|
|Maintainer	|	Oracle Corpoartion	|	PostrateSQL Global Development Group	|
|Max Database Size	| Theoretical Unlimited(256TB)	|	Unlimited	|
|Max Table Size	|	MySAM: 256 TB; InnoDB: 64 TB	|	32 TB 	|
|Suport OS	| YES	|	YES	|
| Usage	| Small to meduim sized Database	|	Meduim sized Database|
|Full-Text
Indexes 	| Full-text indexes can be used only
with MyISAM tables	|	PostgreSQL support full text search
with index. 
	|
| More Popular	|	les Popular	|
| low extensible	| hightly extensible	|
