### ISSUE TITLE
Registration page  not works

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#68]
![image](https://user-images.githubusercontent.com/13945825/92117057-f9626600-edf4-11ea-805a-38031c897bc7.png)

Pressing  **Register button** provides an error --> user is null

**Comment by idrice24** [comment]
in your database create the following tables
mysql> desc user;
+-----------+--------------+------+-----+---------+----------------+
| Field          | Type              | Null  | Key  | Default     | Extra                |
+-----------+--------------+------+-----+---------+----------------+
| user_id      | int(11)           | NO   | PRI    | NULL    | auto_increment |
| active        | int(11)           | YES   |           | NULL    |                           |
| email         | varchar(250) | YES   | UNI    | NULL    |                           |
| last_name | varchar(250)  | YES   |           | NULL    |                           |
| name        | varchar(250)  | YES   |           | NULL    |                           |
| password  | varchar(250)  | YES   |           | NULL    |                           |
| privilage    | varchar(225) | YES   |            | NULL    |                          |
+-----------+--------------+------+-----+---------+----------------+
7 rows in set (0.06 sec)

mysql> desc role;
+----------+--------------+------+-----+---------+-------+
| Field         | Type             | Null  | Key   | Default | Extra |
+----------+--------------+------+-----+---------+-------+
| role_id     | varchar(45)   | NO    | PRI   | NULL    |       |
| name       | varchar(250) | YES   |          | NULL    |       |
| lastName | varchar(250) | YES   |         | NULL    |       |
| email       | varchar(250) | YES    |         | NULL    |       |
| password | varchar(250) | YES   |         | NULL    |       |
| role          | varchar(45)   | YES   |         | NULL    |       |
+----------+--------------+------+-----+---------+-------+
6 rows in set (0.06 sec)

mysql> desc user_role;
+---------+---------+------+-----+---------+----------------+
| Field       | Type      | Null   | Key   | Default | Extra          |
+---------+---------+------+-----+---------+----------------+
| user_id   | int(11)   | NO     | PRI | NULL      | auto_increment |
| role_id    | int(11)   | NO    | PRI | NULL       |                          |
+---------+---------+------+-----+---------+----------------+
2 rows in set (0.01 sec)

**Comment by Ghislain1** [comment]
**User** Table and **Role**  Table are available on DB but empty.( That is ok)

**Comment by idrice24** [comment]
the registration page is now ok!!
the problem was at the level of the Entity
but now i am facing another problem... the table user_role does not filled automatically
