### ISSUE TITLE
Generating a status badge for circleci is wrong!!

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#70]
The way you generate status for cicleci is wrong

This is link for how to do it !!

https://circleci.com/docs/2.0/status-badges/

NB: Color should update  automatically!!

**Comment by Ghislain1** [comment]
<PROJECT_NAME> - Your project’s name. Example: circleci-docs.
<ORG_NAME> - The organization or user name the project in question belongs to.
<VCS> - your VCS provider (gh for “github” and bb for BitBucket).
<LINK> - The link you want the status badge to go to when clicked (example: the pipeline overview page).

**Comment by idrice24** [comment]
done!!
