### ISSUE TITLE
JUNIT tests are missing!!

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#8]
Your whole projects are mising Units Tests  using JUNIT
**TODO:**
-  Checks the advantages of  writing a  Unit test of you source code
-  Find out a sample project or tutorial using JUNIT
- Add  dependencies JUNIT to maven.
- Structure your tests projects by looking at other

**SOME NICES LINKS:**
- https://github.com/junit-team/junit5-samples/tree/r5.6.2/junit5-jupiter-starter-maven

**Comment by idrice24** [comment]
## Advantages of Units Tests in a project
- Makes the Process Agile (A methodology). One of the main benefits of unit testing is that it makes the coding process more Agile.(A project subdivided into small module to be build and combine after into a single module)
- Quality of Code. Unit testing improves the quality of the code
- Debugging Process ( ie If a test fails, then only the latest changes made in the code need to be debugged).
