### ISSUE TITLE
Continuous integration is missing in your project

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/School-Management-Software#9]
CL is missing
**TODO:**
-  Lists advantages( at least 4) of this requirement e.g.  
      a1) Test your over 1 millions code line in minutes
- Find out a sample
- Find out different tools for this purpose
CL tool: e.g. CL TRavis
**SOME LINKS:**
- http://www.ingloriousmind.com/blog/automated-builds-for-your-projects-on-github/
- https://travis-ci.org/

**Comment by idrice24** [comment]
done!
